"""Act II's people, the Azure Expanse (docs/architecture/npc_engine.md): Cloudgate Port and the Thunderhorn Plains, the
Rimefrost hermit and the Grey Pilgrim, Nine Peaks, the Gale Canyons and Ironroot Hold, the Oasis of Bones, the
Shipwrights' Yard, the Starsea Launch and the Trial Hall. Their rooms are the side view's until a room batch brings
them onto the grid."""
from content.npcs.spec import look, npc, place


NPCS = [
    # Cloudgate Port and the Thunderhorn Plains (Azure Expanse, v1.1).
    npc("warden_cao", "Warden Cao", "Nine Peaks toll warden",
        look("topknot", "disciple:indigo", "martial:ink", "boots", hat="guan", weapon="spear"),
        ["Every sky road in the Expanse belongs to the Nine Peaks Alliance.",
         "Toll first, questions after. The Factor's hall is in the market."], ["Toll tokens, please.", "Next!"],
        tree="warden_cao", concealed=["A low realm on the sky roads? Pay your toll and stay out of the Alliance's way."],
        at=["ae_landing"]),
    npc("alliance_guard", "Alliance Guard", "Nine Peaks patrol",
        look("short_knot", "disciple:indigo", "martial:indigo", "boots", weapon="spear"),
        ["Keep your Qi to yourself inside the port.", "Nine peaks, one law. The Alliance's."], ["Move along."],
        concealed=["Weak Qi and loud boots. Walk softly in the port, junior."],
        at=["ae_landing", place("np_alliance_gate", "npc_alliance_guard_np")]),
    npc("wanderer_jiang", "Jiang", "Independent cultivator",
        look("flowing", "vneck:grey", "straight:ink", "boots", cape="tattered", weapon="sword"),
        ["The Alliance calls us 'unaffiliated'. We call ourselves free.",
         "Valley folk come through that gate every few years. Most go home."], ["Hm. Fresh from the valley."],
        concealed=["Smart. Look weak, and the Alliance ignores you. The bandits won't, mind."], at=["ae_landing"]),
    npc("factor_ruan", "Factor Ruan", "Alliance factor",
        look("long_tied:1", "scholar:indigo", "scholar:ink", "folded", hat="guan", cape="solid"),
        ["Stormsteel, stormsilk, fair Alliance prices.", "Spirit Stones only. Taels are for the valley."],
        ["Alliance-grade goods!"], services=["shop:alliance_factor"],
        concealed=["Stormsteel is for Sages. Are you buying for your master?"], at=["ae_port_market"]),
    npc("peddler_gou", "Peddler Gou", "Sky road peddler", look("short_knot:5", "vneck:ochre", "loose", "folded", hat="straw"),
        ["Pills, charms, rice balls. Everything a traveller forgets.",
         "I've walked every sky road twice. Once to go, once to come back for my hat."], ["Traveller's goods!"],
        services=["shop:port_peddler"],
        concealed=["Newcomer? Everyone below Sage buys the storm charm. Everyone. Trust me."], at=["ae_port_market"]),
    npc("smith_hong", "Smith Hong", "Stormsteel smith", look("short_knot", "sleeveless:crimson", "martial", "boots"),
        ["Stormsteel wants a Sage's hands. Before that, it bites.",
         "Lightning Scar ore, spark pelt for the grip. That's the recipe."], ["*crackle* *clang*"],
        services=["shop:stormsteel_smith", "page:guild"], service_labels={"page:guild": "Guild Master exams"},
        at=["ae_port_market"]),
    npc("apothecary_wu", "Apothecary Wu", "Port apothecary", look("ponytail:3", "cardigan:jade", "scholar", "slippers"),
        ["Storm blood is real. Newcomers bleed Qi into the wind until they attune.",
         "A Storm Blood Pill buys you half an hour of patience."], ["Remedies!"],
        services=["shop:port_apothecary", "page:guild"], service_labels={"page:guild": "Guild Master exams"},
        at=["ae_port_market"]),
    npc("sky_sailor_pei", "Sailor Pei", "Sky-ship hand", look("short_knot", "vneck:cloud", "cuffed", "boots", hat="headband"),
        ["Never look down from a sky-ship. Look at the sails.",
         "The Alliance ships run to Nine Peaks. When they feel like it."], ["Heave!"], at=["ae_port_market"]),
    npc("sky_sailor_ning", "Sailor Ning", "Sky-ship hand", look("ponytail", "vneck:indigo", "cuffed", "boots", hat="headband"),
        ["The Qi cushion under the keel? Twelve stones a day to keep it fed.",
         "Storms on the plains sink ships. We go round."], ["Mind the ropes!"], at=["ae_skydock"]),
    npc("dockmaster_fu", "Dockmaster Fu", "Skydock master",
        look("topknot:5", "scholar:ochre", "scholar:grey", "folded", hat="tied"),
        ["No berths for private ships without Alliance papers.",
         "The Condensing Hall? Behind me. Mind the alchemist; she bites harder than the smith."], ["Berths full!"],
        at=["ae_skydock"]),
    npc("innkeeper_tang", "Innkeeper Tang", "Wayfarers' Inn", look("long_tied:3", "cardigan:rose", "straight", "slippers"),
        ["Rooms by the night, soup by the bowl, gossip for free.",
         "The broker in the corner? Pays her bill. That's all I ask."], ["Soup's on!"], services=["shop:wayfarers_inn"],
        concealed=["The cheap room's in the attic. Draughty, but honest, like the price."], at=["ae_wayfarers_inn"]),
    npc("broker_mu", "Broker Mu", "Free broker",
        look("flowing:1", "cardigan:ink", "straight:ink", "boots", hat="weimao", cape="solid"),
        ["I sell what the Alliance doesn't want sold. Mostly, the truth.",
         "Your blood is still valley-soft. The storms here will drink it."], ["Information, fairly priced."],
        services=["shop:free_market"], tree="broker_mu",
        at=["ae_wayfarers_inn", place("np_hall_of_nine", "npc_broker_mu_np")]),
    npc("alchemist_fen", "Alchemist Fen", "Condensing Hall",
        look("long_tied:1", "scholar:white", "scholar:grey", "folded", hat="guan"),
        ["Sage Qi is True Qi pressed until it remembers it was once light.",
         "Bring me thunder and I'll condense it into something you can swallow."], ["Don't touch the furnace."],
        services=["shop:condensing_hall"], at=["ae_condensing_hall"]),
    npc("herder_suo", "Old Suo", "Thunderhorn herder",
        look("short_knot:5", "vneck:earth", "loose", "boots", hat="tied", cape="tattered"),
        ["The thunderhorns aren't cruel. They're just very sure of where they're going.",
         "Stew's hot. Stones, not taels, I'm afraid."], ["Easy, easy..."], services=["shop:herders_camp"],
        at=["tp_herders_camp"]),
    npc("herder_a_lan", "A-Lan", "Herder's daughter", look("ponytail", "cardigan:crimson", "cuffed", "boots"),
        ["Spark weasels steal the lightning out of the grass. Then they spit it at you!",
         "Grandpa Suo says the storms remember everyone who crosses."], ["Hup! Hup!"], scale=0.9, at=["tp_herders_camp"]),
    # Rimefrost Heights and Mirrorwater Lake.
    npc("hermit_shuang", "Hermit Shuang", "Rimefrost hermit",
        look("flowing:5", "scholar:white", "scholar:grey", "folded", cape="tattered"),
        ["...", "Snow keeps every footprint until the wind decides otherwise.", "Silence is not empty. Listen."],
        ["...", "Hm."], at=["rf_hermits_ice_cave"]),
    npc("grey_pilgrim", "The Grey Pilgrim", "A stranger",
        look("long_tied:5", "scholar:grey", "scholar:grey", "folded", hat="weimao", cape="solid"),
        ["You carry the valley's river on you. How quaint.",
         "Every shard finds its way home in the end. I only help them along."], ["..."], tint="#dfe2ea",
        tree="grey_pilgrim", concealed=["A mask over a mask. How quaint. I see the river under both."],
        at=["rf_frostpine_climb", place("ts_throne", "npc_grey_pilgrim_tomb")]),
    # Nine Peaks, the Gale Canyons and Ironroot Hold (Phase C).
    npc("envoy_lanshi", "Envoy Lanshi", "Alliance envoy",
        look("long_tied", "scholar:indigo", "scholar:indigo", "folded", hat="guan", cape="solid"),
        ["Nine peaks, nine seats, one voice. Mine, today.", "The Alliance keeps the sky roads open. Someone has to."],
        ["The Hall is in session."], tree="envoy_lanshi", at=["np_hall_of_nine"]),
    npc("elder_zhong", "Elder Zhong", "First Peak elder",
        look("flowing:5", "scholar:white", "scholar:grey", "folded", hat="guan", cape="solid"),
        ["The First Peak remembers when there was no Alliance. There were more graves then.",
         "A Hollow shard in the wrong hands is a war waiting for a reason."], ["Hm."], tree="elder_zhong",
        concealed=["Hiding your realm on the First Peak? The Alliance notices those who make themselves small."],
        at=["np_hall_of_nine"]),
    npc("auctioneer_tong", "Auctioneer Tong", "Auction Pavilion",
        look("topknot:1", "scholar:crimson", "scholar:ink", "folded", hat="guan"),
        ["Lots at dawn, hammers at dusk. Bid with your head, pay with your stones.",
         "The limit is in the other bidder's heart. Find it."], ["Going once!"], services=["page:auction"],
        service_labels={"page:auction": "Today's lots"}, service_unlocks={"page:auction": "auction_house"},
        at=["np_auction_pavilion"]),
    npc("champion_qiao", "Champion Qiao", "Presence Terrace",
        look("topknot", "disciple:indigo", "martial:ink", "boots", hat="guan", weapon="spear"),
        ["Presence is the weight a cultivator puts on the air. Show me yours.",
         "Nine peaks, nine styles. I've learned eight."], ["Again."], services=["spar:alliance_champion"],
        service_labels={"spar:alliance_champion": "Spar"},
        concealed=["Hiding your weight? The Terrace will find it. Presence does not lie, even when you do."],
        at=["np_presence_terrace"]),
    npc("tollkeeper_bai", "Tollkeeper Bai", "Canyon Mouth toll",
        look("short_knot:5", "vneck:indigo", "loose:earth", "boots", hat="straw", weapon="spear"),
        ["Ten stones a crossing. Alliance tokens pass free.", "Brigands in the canyon wear veils. Honest folk don't."],
        ["Toll!"], concealed=["Ten stones. For someone at your realm the canyon costs more than stones. Think on it."],
        at=["gc_canyon_mouth"]),
    npc("ironroot_warden", "Warden Tie Shan", "Ironroot gatekeeper",
        look("short_knot:4", "sleeveless:earth", "martial:earth", "boots", hat="headband", weapon="staff"),
        ["The Ironroot don't bend. We grow around things.", "Outsiders come to the Hold for iron. Few come for kin."],
        ["Halt."], services=["spar:ironroot_warden"], service_labels={"spar:ironroot_warden": "Test your root"},
        at=["ir_hold_gate"]),
    npc("matriarch_tie", "Matriarch Tie Yun", "Ironroot matriarch",
        look("long_tied:5", "cardigan:earth", "straight:ink", "boots", hat="headband", cape="solid"),
        ["Blood is who you were born to. Roots are who you choose to hold.",
         "Our ancestors sit in the Hall. They're picky about company."], ["The Hold is well."], tree="matriarch_tie",
        at=["ir_clan_hearth"]),
    npc("clan_smith_gang", "Smith Gang", "Ironroot forge", look("short_knot", "sleeveless:earth", "martial", "boots"),
        ["Iron from the roots, fire from the canyon wind. Best forge in the Expanse.",
         "Kin get the good steel. Guests get the rest."], ["*CLANG*"], services=["shop:ironroot_clan"],
        at=["ir_clan_hearth"]),
    # Phase D: the Oasis of Bones.
    npc("oasis_keeper_meng", "Keeper Meng", "Oasis of Bones",
        look("long_tied:3", "vneck:ochre", "loose:earth", "boots", hat="weimao"),
        ["Water is free. Shade is free. Everything else costs stones, because the caravans stopped coming.",
         "Drink before the heat asks you to. By then it's late."], ["Water here."], services=["shop:oasis_keeper"],
        concealed=["Water is free, even for the weak. The sand is not so generous."], at=["sd_oasis_of_bones"]),
    npc("bone_reader_xiu", "Bone-Reader Xiu", "Diviner of the oasis",
        look("flowing:5", "scholar:ink", "scholar:ochre", "folded", cape="solid"),
        ["The bones remember the sand kings. I only read them aloud.",
         "Every crack in a shoulder blade is a road. Most end in the tomb."], ["The bones are warm today."],
        tree="bone_reader_xiu", at=["sd_oasis_of_bones"]),
    # Phase E: the Shipwrights' Yard, the Skyport Wreck, the Trial Hall.
    npc("navigator_sun", "Navigator Sun", "Star navigator",
        look("flowing:1", "scholar:indigo", "scholar:ink", "folded", hat="straw", cape="solid"),
        ["The Starsea has no roads. Only stars, and the lines we draw between them.",
         "A chart is four readings and the patience to trust them. Most sailors have the readings."], ["Mind the table."],
        services=["shop:navigator"], concealed=["The Starsea eats small realms whole. Are you sure you want a chart?"],
        at=["ae_shipyard"]),
    npc("shipwright_lao", "Shipwright Lao", "Skydock shipwright",
        look("short_knot:4", "sleeveless:ochre", "martial:earth", "boots", hat="headband"),
        ["A hull is a formation you can stand on. Get one line wrong and the Starsea finds it.",
         "Spirit wood for the ribs, stormsteel for the keel, harpy plumes for the sail. The plumes are the hard part."],
        ["*tok tok tok*"], services=["shop:shipwright"], at=["ae_shipyard"]),
    npc("launch_warden_he", "Warden He", "Starsea Launch",
        look("topknot:5", "vneck:white", "straight:indigo", "boots", hat="straw"),
        ["The ring was built to throw ships at the stars. It has not thrown one in two hundred years.",
         "On clear nights you can see lanterns out there. Nobody hangs them. They are just there."], ["The ring is quiet."],
        at=["sw_starsea_launch"]),
    npc("trial_master_wen", "Trial Master Wen", "Trial Hall",
        look("flowing", "scholar:white", "scholar:indigo", "folded", hat="guan", cape="solid"),
        [
         "Eight seats, eight Presences. The ninth seat waits for whoever can sit under the other eight and stay themselves.",
         "Will is not stubbornness. Stubbornness breaks. Will bends and comes back."], ["Sit up straight."],
        at=["np_trial_hall"]),
]
