"""Act III's people, the Lantern Star Field (docs/act3_design.md; docs/architecture/npc_engine.md): Lanternfall Harbor
and the Drifting Shoals, Blackmast Haven and the Wyrmnest Isles, the Star Warden Citadel and the Orbit Ruins, the
Ashen Reach and the Tidebreak Front. Their rooms are the side view's until a room batch brings them onto the grid."""
from content.npcs.spec import look, npc


NPCS = [
    # Phase A: Lanternfall Harbor and the Drifting Shoals.
    npc("harbormaster_lin", "Harbormaster Lin", "Lanternfall Harbor",
        look("short_knot:5", "vneck:indigo", "cuffed:ink", "boots", hat="straw"),
        ["Skiffs from the Expanse come in once a generation. You are early.",
         "Every island out there has a lantern over it. When one goes dark, we stop sending boats."],
        ["Mind the lines!", "Tide's high on the stars tonight."], tree="harbormaster_lin", at=["lh_arrival_quay"]),
    npc("warden_xiao", "Warden Xiao Ning", "Star Warden of the harbour",
        look("high_pony", "disciple:white", "martial:indigo", "boots", hat="guan", cape="solid", weapon="spear"),
        ["The Wardens keep the lanterns lit. Everything else out here is somebody else's problem, until it isn't.",
         "Your Will is loud. Out here that is a compliment."], ["Eyes on the dark.", "Keep your Presence in, visitor."],
        tree="warden_xiao", at=["lh_arrival_quay"]),
    npc("clerk_yu", "Clerk Yu", "Harbour exchange", look("topknot:1", "scholar:cloud", "scholar:grey", "folded", hat="guan"),
        ["A hundred Spirit Stones to the crystal, less the Wardens' fifth. The rate has not moved in four hundred years.",
         "Star Jade is for savings. Nobody spends Star Jade."], ["Next."], at=["lh_harbor_market"]),
    npc("peddler_ning", "Peddler Ning", "Harbour peddler",
        look("ponytail:3", "cardigan:ochre", "straight", "slippers", hat="weimao"),
        ["Jelly silk wraps, fresh from the Shoals! They only sting a little."], ["Silk! Glowing silk!"],
        services=["shop:lanternfall_goods"], at=["lh_harbor_market"]),
    npc("apothecary_sang", "Apothecary Sang", "Harbour apothecary",
        look("long_tied:4", "cardigan:jade", "scholar:grey", "folded"),
        ["Star Lotus clears the soul like cold water clears a cup. Too much and you forget your own name."],
        ["Mind the jars."], services=["shop:lanternfall_apothecary"], at=["lh_harbor_market"]),
    npc("smith_ou", "Smith Ou", "Harbour forge",
        look("short_knot:4", "sleeveless:earth", "martial:earth", "boots", hat="headband"),
        ["Driftglass lenses, star iron, lantern bronze. I work what the Field gives me."], ["*clang*"],
        at=["lh_harbor_market"]),
    npc("chandler_shu", "Chandler Shu", "Lantern-maker and scholar",
        look("flowing:1", "scholar:white", "scholar:ink", "folded", hat="guan", cape="solid"),
        ["A lantern is a sentence with one word in it: stay. Every cage out there says it to a star.",
         "Read before you fight. It is cheaper."], ["Hm. Mind the wicks."], tree="chandler_shu", at=["lh_star_chandlery"]),
    npc("innkeeper_fei", "Innkeeper Fei", "Tidelight Inn", look("long_tied:2", "cardigan:rose", "straight", "slippers"),
        ["Rooms face the lanterns. The ones facing the dark are cheaper."], ["Tea's hot."], at=["lh_tidelight_inn"]),
    npc("hulk_keeper_bo", "Old Bo", "Keeper of the Moored Hulks",
        look("short_knot:5", "vneck:grey", "cuffed", "folded", hat="straw"),
        ["These hulls sailed here before your grandfather's grandfather. Now they hold my beans."],
        ["Hm.", "Sit, if you like. The deck doesn't mind."], tree="hulk_keeper_bo", at=["dr_moored_hulks"]),
    # Phase B: Blackmast Haven and the Wyrmnest Isles.
    npc("deckhand_mo", "Deckhand Mo", "Escaped from the Blackmast",
        look("short_knot:3", "sleeveless:grey", "cuffed:ink", "boots", hat="headband"),
        [
         "Three years I swabbed that flagship. The Admiral keeps a purser now: old, clever, scared of everything but money.",
         "Spike the cannons and the gangway comes down. They only raise it when the battery can cover the deck."],
        ["Keep your head down."], tree="deckhand_mo", at=["bm_blackmast_docks"]),
    # Phase C: the Star Warden Citadel, the Orbit Ruins, and the Star Chandlery's lanternwright.
    npc("warden_commander_yao", "Warden-Commander Yao", "Commander of the Star Wardens",
        look("long_tied:4", "disciple:white", "martial:indigo", "boots", hat="guan", cape="solid", weapon="spear"),
        [
         "Forty lanterns when I took this command. Twenty-eight tonight. Every one that goes dark, the Tide walks in behind.",
         "A Warden is a Will that has agreed to be a wall. Most people only agree for a while."],
        ["Hold the line.", "Report."], at=["wc_wardens_hall"]),
    npc("stargazer_ming", "Stargazer Ming", "Keeper of the Observatory",
        look("flowing:3", "scholar:ink", "scholar:white", "folded", hat="guan"),
        ["Every Sphere Lord's world is up there somewhere. Small. Turning. Waiting to be recognised.",
         "Presence asks who is stronger. A Sphere answers: here, the rules are mine."],
        ["Mind the lenses.", "Clear skies tonight."], services=["shop:observatory"],
        service_labels={"shop:observatory": "Star-stones"}, at=["wc_observatory"]),
    npc("presence_master_ruo", "Presence-Master Ruo", "Warden of the Presence Court",
        look("topknot:5", "sleeveless:white", "martial:indigo", "boots", cape="solid"),
        ["Hold it. Don't push. Hold. A Presence that pushes is a Presence that tires.",
         "When two Spheres touch, one of them breaks. Make sure you know which before you let them touch."],
        ["Breathe.", "Again, softer."], at=["wc_presence_court"]),
    npc("orbit_hermit", "The Orbit Hermit", "Hermit of the Orbit Ruins",
        look("long_tied:3", "scholar:cloud", "loose:ink", "slippers", cape="solid"),
        ["The first Wardens built a temple to watch the stars turn. Then the island began to turn with them. I stayed.",
         "Space is not empty. It is folded. Learn where the folds are and a step is as long as you like."],
        ["Mind the floor. It moves.", "Hm? Oh. Hello."], at=["or_orbit_garden"]),
    # Phase D: the Ashen Reach and the Tidebreak Front (chapter 21).
    npc("warden_hu_jin", "Warden Hu Jin", "Warden scout of the Ashen Reach",
        look("ponytail:1", "vneck:indigo", "martial:ink", "boots", hat="headband"),
        [
         "The Ashborn do not raid for gold. They raid for fire. Their dead are burned in lantern flame or they do not rest.",
         "Kharn is no bandit. He is a general with a queen and a people behind him, and not enough fire for either."],
        ["Keep low. The cinders carry.", "Eyes east."], at=["ar_cinder_fields"]),
    npc("ashborn_envoy_veyla", "Envoy Veyla", "Ashborn envoy",
        look("long_tied", "scholar:ochre", "martial:ink", "folded", hat="guan", cape="tattered"),
        ["I came to speak for the General. No one on your side has wanted to listen yet.",
         "We burn our dead so they are not taken by the grey. Without lantern fire our dead walk. Would you not raid, for that?"],
        ["Ash to ash.", "I will wait."], at=["ar_war_camp"]),
    npc("warden_captain_duan", "Captain Duan", "Warden-Captain of the Tidebreak Bastion",
        look("topknot", "cardigan:indigo", "martial:ink", "boots", cape="solid", weapon="spear"),
        ["Every lantern on this wall is a Warden who did not go home. We keep them lit.",
         "When the bell rings, the Tide comes. It always comes to the great lantern first."], ["Hold.", "The wall stands."],
        at=["tf_tidebreak_bastion"]),
    npc("quartermaster_bai", "Quartermaster Bai", "Keeper of the Bastion's armoury",
        look("short_knot:4", "disciple:grey", "loose:ink", "boots"),
        ["Brushes and bells. A Warden scribe writes seals on the Hollow; a bellringer stills it. Swords are for the young.",
         "Pay in crystals. The Tide does not take IOUs."], ["Mind the stock.", "Next."], services=["shop:bastion_armoury"],
        service_labels={"shop:bastion_armoury": "The armoury"}, at=["tf_tidebreak_bastion"]),
    npc("tinker_mei", "Tinker Mei", "Keeper of the Copperjaw beetles",
        look("ponytail:2", "sleeveless:earth", "cuffed:ink", "boots", hat="straw"),
        ["My beetles eat metal. The drones are metal that forgot it was metal. You see where this is going.",
         "Feed them ore and they multiply while you sleep. Open the box and they will chew anything near you."],
        ["Click, click.", "Don't shake the box."], at=["tf_tidebreak_bastion"]),
    npc("lanternwright_han", "Lanternwright Han", "Scholar-lanternwright",
        look("flowing:1", "scholar:white", "scholar:indigo", "folded", hat="guan"),
        [
         "The first Wardens wrote 'stay' on every cage and the stars stayed. Words are not weak. They are only rarely meant.",
         "An upright heart writes a stronger glyph. A heart that is not upright should not write at all."],
        ["Straight lines.", "Ink, brush, breath."], services=["shop:lanternwright"],
        service_labels={"shop:lanternwright": "Glyph-scrolls"}, at=["lh_star_chandlery"]),
    npc("tamer_qiu", "Tamer Qiu", "Keeper of the Wyrmnest",
        look("ponytail:2", "vneck:earth", "martial:ochre", "boots", hat="straw"),
        ["The star-wyrms nested here before the Wardens came. Now there is one egg left, and the grey is in the brood.",
         "A beast that was born under a lantern star listens only to a Will that can hold its own shape."],
        ["Hush. They're sleeping."], tree="tamer_qiu", at=["wn_nest_cliffs"]),
]
