"""Stoneford's people (docs/architecture/npc_engine.md): the gate, Market Street, Artisan Row and its guilds, the County
Hall and the Fairground's recruiters and rivals."""
from content.npcs.spec import look, npc, place, work


NPCS = [
    # S49 the mortal kingdom: the county magistrate keeps the hall behind the gatehouse.
    npc("magistrate_qian", "Magistrate Qian", "County magistrate",
        look("long_tied:1", "scholar:indigo", "scholar", "folded", hat="guan"),
        ["The county has more trouble than hands. You have hands.",
         "Cultivators pass through Stoneford like weather. The ones who stop to help are remembered.",
         "Keep your techniques sheathed in the villages. Ordinary people have long memories and short tempers."],
        ["Next petition!", "The county thanks you."], services=["page:county"],
        service_labels={"page:county": "County business"}, at=[place("sf_county_hall", work=work("read", auto=1))]),
    npc("guard_hou", "Captain Hou", "Gate guard", look("topknot", "disciple:earth", "martial", "boots", weapon="spear"),
        ["Stoneford gate. Keep your blades sheathed.", "Recruitment Fair's on the Fairground. West, past Artisan Row."],
        ["Next!", "Move along."],
        concealed=["Kindling, are you? Keep to the road. The Mudwater never went away, not really."],
        at=[place("sf_gate", work=work("spear", auto=2))]),
    npc("foreman_dong", "Foreman Dong", "Quarry foreman", look("short_knot:5", "sleeveless:earth", "loose", "boots"),
        ["Stonewall Quarry needs strong backs.", "Rock beetles again. Curl up, roll, bite. Watch the curl."],
        ["Put your back into it!"],
        at=[place("sf_gate", work=work("carry", auto=2)),
            place("sq_quarry_rim", "npc_dong_rim", work=work("watch", auto=2))]),
    npc("adventurer_kai", "Kai", "Wandering swordsman",
        look("flowing", "vneck:ink", "straight", "boots", cape="tattered", weapon="sword"),
        ["The Caravan Road's gone bad. Bandits call themselves the Mudwater.",
         "I came for the tournament. I stayed for the tea."], ["Anyone up for a spar?"],
        concealed=["You look green. The Caravan Road eats green travellers. Go in daylight, and not alone."],
        at=[place("sf_gate", work=work("sword", auto=1))]),
    npc("storekeeper_fang", "Proprietor Fang", "General store", look("short_knot", "scholar:ochre", "scholar", "folded"),
        ["Teas, rice, charms. If Stoneford needs it, Fang sells it.", "Return charms! Never walk home again!"],
        ["Bargains!"], services=["shop:stoneford_general"],
        concealed=["First time in town? The starter charms are on the low shelf. The good ones would cost you a year."],
        at=[place("sf_market", work=work("sell", auto=1))]),
    npc("auntie_rong", "Auntie Rong", "Tea house", look("long_tied:3", "cardigan:rose", "straight", "slippers"),
        ["Lotus root tea calms the belly and the Qi.", "Sit. Everyone who sits in my tea house leaves stronger."],
        ["Tea! Hot tea!"], services=["shop:stoneford_tea"], at=[place("sf_market", work=work("cook", auto=1))]),
    npc("keeper_shi", "Keeper Shi", "Stone keeper", look("topknot:1", "scholar:jade", "scholar", "folded"),
        ["Teleport stones remember those who touch them.", "A shard of Spirit Stone pays the ferryman of the stones."],
        ["The stones hum today."], at=[place("sf_market", work=work("sell", auto=1))]),
    npc("tailor_xun", "Tailor Xun", "Pouch sewer", look("short_knot:2", "cardigan:indigo", "straight:grey", "folded"),
        ["A Qiankun pouch is only as big as the stitches that fold it. I fold them small.",
         "Four compartments to a pouch. Ore in one, herbs in another. Never mix fish with anything."],
        ["Mind the needles.", "Measure twice, fold once."], services=["page:pouches"],
        service_labels={"page:pouches": "Sew a pouch"}, service_unlocks={"page:pouches": "pouch_sewing"},
        at=[place("sf_market", work=work("sell", auto=1))]),
    npc("courier_lin", "Courier Lin", "Courier", look("ponytail", "vneck:indigo", "cuffed", "boots"),
        ["Letters to every sect, parcels to every village.", "The mail finds you. Somehow. Always."], ["Coming through!"],
        at=[place("sf_market", work=work("carry", auto=2))]),
    npc("adventurer_su", "Su Qing", "Herb hunter", look("high_pony:4", "cardigan:jade", "cuffed", "boots"),
        ["The bamboo grove east of the marsh has ember peppers. And vipers.", "Never eat a mushroom that smiles at you."],
        ["Hm, willow moss..."], at=[place("sf_market", work=work("watch", auto=2))]),
    npc("old_pan", "Old Pan", "Wandering merchant",
        look("topknot:1", "vneck:ochre", "loose", "folded", hat="straw", cape="tattered"),
        ["Rare wares for rare coin. Spirit Stones only.", "I'm here today. Tomorrow? Who knows."], ["Rare wares!"],
        services=["shop:old_pan"],
        concealed=["Spirit Stones only, little one. Come back when your Qi is worth a second look."],
        at=["sf_market", place("wp_east", "npc_old_pan_wp")]),
    npc("smith_bao", "Smith Bao", "Blacksmith", look("short_knot", "sleeveless:ink", "martial", "boots"),
        ["Iron remembers every hammer blow.", "Bring me Jadeiron and I'll make you something that sings."], ["*clang*"],
        services=["shop:stoneford_smith", "page:guild", "shop:forge_guild"], service_labels={"page:guild": "Forge Guild"},
        service_unlocks={"page:guild": "forge_guild", "shop:forge_guild": "forge_guild"},
        concealed=["Soft hands for a blade like that. I'll sharpen it anyway. Maybe it will teach you."],
        at=[place("sf_artisan_row", work=work("hammer", [15.0, 12.6, "e", "anvil"], [13, 13, "s"]))]),
    npc("array_master_ren", "Array Master Ren", "Formation Guild",
        look("long_tied:2", "scholar:cloud", "scholar:ink", "slippers", hat="guan"),
        ["A plate is a formation you can carry. Etch it true and it will hold a wall.",
         "The guild asks for speed, not luck. Stone does not roll dice."], ["Line, line, circle.", "Mind the stone dust."],
        services=["page:guild", "shop:formation_guild"], service_labels={"page:guild": "Formation Guild"},
        service_unlocks={"page:guild": "formation_guild", "shop:formation_guild": "formation_guild"},
        at=["sf_artisan_row"]),
    npc("tinkerer_yu", "Tinkerer Yu", "Tinkerer", look("ponytail:3", "scholar:grey", "cuffed", "folded"),
        ["Tools are just patience you can hold.", "A better pickaxe means more ore and fewer blisters."],
        ["Where's my small spanner?"], services=["shop:tinkerer", "page:workshop"],
        service_labels={"page:workshop": "Puppet bench"}, service_unlocks={"page:workshop": "puppetry"},
        at=[place("sf_artisan_row", work=work("mend", auto=1))]),
    npc("guildmaster_tang", "Guildmaster Tang", "Alchemist Guild",
        look("topknot:4", "scholar:jade", "scholar:ink", "slippers", hat="guan"),
        ["The guild does not care who taught you. It cares what comes out of your furnace.",
         "An exam is a batch of pills against a candle. Nothing more mysterious than that.",
         "Commissions come in every morning. Pay is fair; the guild takes nothing but your good name."],
        ["Mind the candle.", "Another order for Healing Pills. Always Healing Pills."],
        services=["page:guild", "shop:alchemist_guild"], at=["sf_artisan_row"]),
    npc("old_scribe_bai", "Old Scribe Bai", "Talisman master",
        look("topknot:5", "scholar:ink", "scholar", "slippers", hat="guan"),
        ["A talisman is a sentence the world has to finish.", "Steady wrist, one breath, no lifting the brush."],
        ["Mind the ink."], services=["page:talisman"], service_labels={"page:talisman": "Write talismans"},
        service_unlocks={"page:talisman": "talisman"}, at=[place("sf_artisan_row", work=work("write", auto=1))]),
    npc("elder_gu", "Elder Gu", "Trade house master", look("long_tied:1", "scholar:crimson", "scholar", "folded", cape="solid"),
        ["Everything has a price. Most things have two.", "Bring me curiosities and I'll tell you what they're worth."],
        ["Hmm, interesting."], services=["shop:gu_trade_house", "page:workshop"],
        service_labels={"page:workshop": "Appraise"}, service_unlocks={"page:workshop": "appraisal"},
        concealed=["A small cultivator with a heavy purse. Mind who sees you open it."], at=["sf_artisan_row"]),
    npc("madam_hua", "Madam Hua", "Trade house master",
        look("flowing:2", "cardigan:jade", "straight", "slippers", cape="solid"),
        ["The trade house deals fairly now. I promise you that.", "Gu's ledgers made interesting reading."],
        ["Fair prices!"], services=["shop:gu_trade_house"], at=["sf_artisan_row"]),
    npc("mei_qing", "Mei Qing", "Alchemist", look("flowing:3", "cardigan:indigo", "scholar", "slippers"),
        ["A pill is a promise. Keep it simple and it keeps you alive.", "Willow moss, riverreed ginseng, and patience."],
        ["Too hot... too hot!"], services=["shop:mei_qing", "shop:mei_qing_recipes"],
        at=["sf_artisan_row", place("rm_marsh_edge", "npc_mei_qing_marsh")]),
    npc("mei_qing_sect", "Mei Qing", "Visiting alchemist", look("flowing:3", "cardigan:indigo", "scholar", "slippers"),
        ["I teach at both sects. The furnace doesn't care about robes."], ["Mind the fumes."],
        at=[place("ja_alchemy_hall", work=work("cook", auto=1))]),
    npc("apprentice_tao", "Apprentice Tao", "Smith's apprentice", look("short_knot", "sleeveless:earth", "cuffed", "slippers"),
        ["Master Bao says I'll hold a hammer next year.", "Did you know iron can taste angry?"], ["Hot, hot!"], scale=0.9,
        at=[place("sf_artisan_row", work=work("carry", auto=2))]),
    npc("recruiter_qing_lan", "Qing Lan", "Jade Sect recruiter",
        look("high_pony", "disciple:jade", "martial:jade", "boots", weapon="sword"),
        ["The Jade Sect teaches the water's patience and the sword's clarity.",
         "Our academy sits by the river. You'll feel at home."], ["Join the Jade Sect!"], tree="recruiter_jade",
        on_talk=[{"kind": "set_flag", "flag": "met_recruiter_jade"}], at=["sf_fairground"]),
    npc("recruiter_mo_yun", "Mo Yun", "Cloud Sect recruiter",
        look("topknot", "disciple:cloud", "martial:cloud", "boots", weapon="staff"),
        ["The Cloud Sect climbs. Our monastery touches the clouds.", "Wind cannot be held. Neither can a Cloud disciple."],
        ["The Cloud Sect awaits!"], tree="recruiter_cloud", on_talk=[{"kind": "set_flag", "flag": "met_recruiter_cloud"}],
        at=["sf_fairground"]),
    npc("shen_lian", "Shen Lian", "Cloud Sect disciple", look("high_pony", "disciple:cloud", "martial:cloud", "boots"),
        ["We picked different sects. Doesn't mean I'll go easy on you.", "Spar me at the practice yard. I'm faster now."],
        ["Still slow?"], services=["spar:shen_lian"], service_labels={"spar:shen_lian": "Spar"}, at=["sf_fairground"]),
    npc("wen_zhao", "Wen Zhao", "Rival", look("flowing", "disciple:ink", "martial:ink", "boots", cape="solid", weapon="sword"),
        ["The tournament finals. You and me. Don't disappoint.", "Talent is a door. You still have to walk through it."],
        ["Hmph."], services=["spar:wen_zhao"], service_labels={"spar:wen_zhao": "Spar"}, at=["sf_fairground"]),
    npc("fair_vendor_he", "Vendor He", "Fair vendor", look("short_knot:5", "vneck:rose", "loose", "slippers"),
        ["Candied hawthorn! Sect badges! Lucky charms!", "Buy a lucky charm. Can't hurt."], ["Hawthorn! Sweet hawthorn!"],
        at=[place("sf_fairground", work=work("sell", auto=1))]),
    npc("adventurer_rui", "Rui", "Retired disciple", look("topknot:5", "scholar:grey", "straight", "folded"),
        ["I washed out at Heart Tempering. The Heart Trial shows you things.",
         "Pick the sect whose method suits your breath, not your pride."], ["Ah, youth."],
        at=[place("sf_fairground", work=work("watch", auto=2))]),
]
