"""Act I side quests of the valley (Part 8, "about 35 side quests"): small threads for the people of Lotus Ferry,
Stoneford, Greyreed Hamlet and the gorge who had none. Placed by story.py's side_quests() (section act1)."""
from common import realm, unlocked
from content.quests.spec import side, clear, fetch, deliver, talk, spar, reach, step, item, fx

QUESTS = [
    side("nets_and_shells", fetch("crab_shell", 5, "Bring Mudshell Crab shells"), giver="fisher_wen",
         offer="The crabs cut my nets to ribbons. Bring me their shells and I'll patch the nets with them. Fair's fair.",
         done="Ha! Crab-shell floats. They'll never live it down. Here, supper.", gives=[item("roast_fish", 2)]),
    side("the_muddy_wash", clear("reedtail_rat", 6, "Chase the Reedtail Rats off the washing lines"), giver="washer_mei",
         offer="Rats in the reeds again. They chew the lines and drag the washing through the mud. Six of them, at least.",
         done="Clean sheets for once. Bless you.", realm="bone_forging_3"),
    side("beetle_shell_lacquer", fetch("beetle_shell", 6, "Bring Rock Beetle shells"), giver="storekeeper_fang",
         offer="Ground beetle shell makes the finest lacquer in the valley. The quarry beetles are too tough for my porters.",
         done="Look at that shine. The Jade Sect will pay double for boxes like these."),
    side("copper_for_the_bellows", fetch("copper_ore", 8, "Bring Copper ore"), giver="smith_bao",
         offer="My bellows need new copper fittings and the quarry price doubled. Mine me some, would you?",
         done="Good ore. Take my old hammer. It still rings true.", realm="bone_forging_5", target_room=None,
         pay=100, gives=[item("forge_hammer", 1)]),
    side("auntie_rongs_soup", deliver("riverfish_soup", 2, "Bring Riverfish Soup"), giver="auntie_rong", name="Auntie Rong's Soup",
         offer="My hands shake too much to gut fish these days. Two bowls of riverfish soup for my grandsons?",
         done="Just like my mother made. Take some tea, dear.", realm="bone_forging_8", needs=[unlocked("cooking")],
         pay=80, gives=[item("lotus_root_tea", 2)]),
    side("kais_wager", clear("mud_hound", 6, "Defeat Mud Hounds at the Mudwater stockade"), giver="adventurer_kai", name="Kai's Wager",
         offer="I bet Rui you could clear the stockade kennels before I could. Don't make me lose.",
         done="Ha! Rui owes me a month of dumplings. Here's your cut.", realm="qi_kindling_7", pay=150),
    side("su_qings_map", reach("wg_echo_cliffs", "Reach the Echo Cliffs"), clear("boulder_serpent", 3, "Drive off Boulder Serpents"),
         giver="adventurer_su", name="Su Qing's Map",
         offer="I'm charting the gorge for the cartographers' guild. The serpents on the Echo Cliffs keep eating my surveyors' lunch.",
         done="The ledge is clear. My map will have your name in the corner.", realm="heart_tempering_3", pay=250,
         gives=[item("spirit_stone_low", 2)]),
    side("mins_first_caravan", clear("gorge_bandit_adept", 5, "Clear the gorge bandits from the caravan road"), giver="hamlet_trader_min",
         name="Min's First Caravan", after="market_day",
         offer="Greyreed's first caravan leaves for Stoneford tomorrow. The gorge bandits know it too.",
         done="The caravan made it! Greyreed is a real trade post now.", pay=None, gives=[item("spirit_stone_low", 3)]),
    # S49 grudges: the Gorge Bandits' feud with Greyreed ends in a fair fight with their chief.
    side("old_scores", spar("gorge_chief", "Settle it hand to hand with Chief Yan Bo at the Gorge Mouth"), giver="hamlet_trader_min",
         after="mins_first_caravan",
         offer=["The Gorge Bandits and Greyreed have old scores. Their chief says he'll call it even if someone beats him fairly. No knives, no crowd.",
                "He waits at the Gorge Mouth. Win, and the feud is over. For Greyreed, and for you."],
         done="Yan Bo sent word: the Gorge is quiet for Greyreed. And for you. I didn't think I'd live to see it.", pay=300),
    side("wen_zhaos_challenge", spar("wen_zhao", "Beat Wen Zhao in a rematch"), giver="wen_zhao", name="Wen Zhao's Challenge",
         after="the_valley_finals", offer="The finals were luck. Face me again, here, with no crowd to cheer for you.",
         done="...Not luck, then. Next time I'll be ready.", pay=None, gives=[fx("grant_title", title="rivals_respect")]),
    side("guos_old_wound", fetch("willow_salve", 1, "Bring Willow Salve"), giver="uncle_guo", name="Guo's Old Wound",
         offer="My old meridian wound aches. Granny's salve helps.", done="Ahh. Better.", realm="qi_kindling_3",
         target_room="lf_village", pay=80),
    side("the_broken_kindling", fetch("qi_gathering_pill", 2, "Bring Qi Gathering Pills"), giver="uncle_guo",
         after="guos_old_wound", offer="I want to try again. Kindling. Help me?", done="We'll see.", target_room=None),
    side("a_second_try", talk("uncle_guo", "Watch Uncle Guo meditate"), giver="uncle_guo", hand_in="", after="the_broken_kindling",
         realm="qi_unfurling_1", offer="Stay with me while I try.", done="Qi Kindling 1. At my age! Ha!", pay=None,
         gives=[fx("grant_title", title="guos_student")]),
    side("dous_kite_returns", deliver("cloud_feather", 1, "Bring a Cloud Feather for the new kite"), giver="little_dou",
         name="Dou's Kite Returns", requires={"all": [realm("bone_forging_3"), {"kind": "quest_done", "quest": "the_runaway_kite"}]},
         offer="I'm making a kite that flies to the clouds! I need a cloud feather.", done="It flies! Sort of!", pay=50),
    side("dou_wants_to_train", step("hit_object", "Show Dou how to punch the stump", 20, type="training_stump"), giver="little_dou",
         after="dous_kite_returns", offer="Teach me to punch! Please please please.", done="Hi-YAH! Did you see?!", pay=None,
         gives=[fx("grant_title", title="big_sibling")]),
    # Part 8 (Hamlet Square): the grey roofs' lanterns are cleansed by hand, one on the hall and one on the granary
    # (inspect objects in gh_hamlet_square that set these flags; the hamlet opens at the quest's own realm).
    side("grey_roofs", clear("hollowed_boarlet", 10, "Clear the Hollowed from the Grey Pools"),
         step("set_flag", "Cleanse the grey lantern on the hall roof", flag="grey_lantern_hall"),
         step("set_flag", "Cleanse the grey lantern on the granary roof", flag="grey_lantern_granary"), giver="hamlet_elder_gao",
         offer="The grey came up from the pools and settled on our roofs. Clear the Hollowed from the pools, and wipe "
               "the grey from the lanterns on the hall and the granary. Then we can walk home.",
         done="The lanterns burn and the road home is open.", realm="heart_tempering_1", pay=120),
    side("cleansing_the_well", step("set_flag", "Cleanse the hamlet well", flag="well_cleansed"), giver="hamlet_elder_gao",
         after="grey_roofs", target_room="gh_hamlet_square", on_accept=[item("cleansing_pill", 1)],
         offer="The well. If it runs clear, we stay.", done="Clear water. Thank you.", pay=150),
    side("market_day", deliver("rice", 10, "Deliver Rice"), giver="hamlet_elder_gao", after="cleansing_the_well",
         offer="A market needs goods. Rice to start.", done="Greyreed trades again!"),
    side("old_pans_errand_1", deliver("ember_pepper", 5, "Bring Ember Peppers"), giver="old_pan", name="Old Pan's First Errand",
         needs=[unlocked("appraisal")], offer="Peppers. Five.", done="Spicy. Good.", pay=None, gives=[item("spirit_stone_low", 2)]),
    side("old_pans_errand_2", deliver("pearl", 1, "Bring a Pearl"), giver="old_pan", name="Old Pan's Second Errand",
         after="old_pans_errand_1", offer="A pearl. From the tide crabs.", done="Lovely.", pay=None, gives=[item("spirit_stone_low", 4)]),
    side("old_pans_errand_3", deliver("mist_lotus", 2, "Bring Mist Lotus"), giver="old_pan", name="Old Pan's Third Errand",
         after="old_pans_errand_2", offer="Mist lotus. Two.", done="I'll keep something special for you from now on.", pay=None,
         gives=[fx("set_flag", flag="pan_rotation_plus")]),
]
