class_name TrainingSectAuthority
extends Authority
## S20 · Training sect membership, rank, contribution and reputation per
## character. Daily missions are generated by the Quest authority on daily_reset.

func intents() -> Array:
	return ["take_promotion_trial", "leave_sect", "set_sect_role", "buy_sect_node"]

func handle(intent: Dictionary) -> Dictionary:
	var c = char_of(intent)
	if c == null: return fail("no_character")
	match str(intent.type):
		"take_promotion_trial": return promote(c)
		"leave_sect": return fail("not_in_valley", {"text": Tx.t("sim.training_sect.leaving_your_sect_is_not")})
		"set_sect_role": return set_role(c, str(intent.get("role", "")))
		"buy_sect_node": return buy_node(c, str(intent.get("branch", "")))
	return fail("unknown_intent")

# ------------------------------------------------------------------ S48 sect role variants (v0.9)
## The signature line's variant: "damage" or "support". The first choice is free; changing it costs contribution.
func set_role(c, role: String) -> Dictionary:
	var sid := str(c.training_sect.get("id", ""))
	var roles := ContentDB.entry("sect_roles", sid)
	if roles.is_empty() or not (roles.get("variants", {}) as Dictionary).has(role): return fail("unknown_role")
	var cfg: Dictionary = ContentDB.config("sect_roles")
	if not RequirementRules.passes({"all": [{"kind": "sect_rank_at_least", "rank": str(cfg.get("role_rank", "outer_disciple"))}]}, game.ctx(c)):
		return fail("rank", {"text": Tx.t("sim.training_sect.role_rank")})
	var now := str(c.training_sect.get("role", ""))
	if now == role: return ok({"role": role})
	var cost := int(cfg.get("switch_cost", 50)) if now != "" else 0
	if int(c.training_sect.get("contribution", 0)) < cost: return fail("contribution", {"text": Tx.t("sim.training_sect.not_enough_contribution") % cost})
	if cost > 0: apply_contribution(c.id, -cost, "sect_role")
	c.training_sect["role"] = role
	emit("sect_role_chosen", {"actor": c.id, "sect": sid, "role": role, "cost": cost})
	return ok({"role": role})

## The next node of one branch of the sect tree, bought with contribution (some need a higher rank).
func buy_node(c, branch: String) -> Dictionary:
	var sid := str(c.training_sect.get("id", ""))
	if sid == "": return fail("no_sect")
	var b := tree_branch(branch)
	if b.is_empty(): return fail("unknown_branch")
	var tree: Dictionary = c.training_sect.get("tree", {})
	var lvl := int(tree.get(branch, 0))
	var nodes: Array = b.get("nodes", [])
	if lvl >= nodes.size(): return fail("complete")
	var node: Dictionary = nodes[lvl]
	if node.has("rank") and not RequirementRules.passes({"all": [{"kind": "sect_rank_at_least", "rank": str(node.rank)}]}, game.ctx(c)):
		return fail("rank", {"text": Tx.t("req.sect_rank") % str(node.rank).replace("_", " ").capitalize()})
	var cost := int(node.get("cost", 0))
	if int(c.training_sect.get("contribution", 0)) < cost: return fail("contribution", {"text": Tx.t("sim.training_sect.not_enough_contribution") % cost})
	apply_contribution(c.id, -cost, "sect_tree")
	tree[branch] = lvl + 1
	c.training_sect["tree"] = tree
	emit("sect_node_bought", {"actor": c.id, "sect": sid, "branch": branch, "node": lvl + 1})
	return ok({"branch": branch, "node": lvl + 1})

static func tree_branch(branch: String) -> Dictionary:
	for b in ContentDB.config("sect_roles").get("tree", {}).get("branches", []):
		if str(b.id) == branch: return b
	return {}

func apply_join(actor_id: String, sect_id: String) -> void:
	var c = game.character(actor_id)
	var sect := ContentDB.entry("sects", sect_id)
	if c == null or sect.is_empty() or str(c.training_sect.get("id", "")) != "": return
	c.training_sect = {"id": sect_id, "rank": "service_disciple", "contribution": 0, "reputation": {sect_id: 10}}
	for m in sect.get("methods", []): game.progression.apply_learn_method(actor_id, str(m))
	if sect.has("token"): game.inventory.apply_add(actor_id, str(sect.token), 1, "sect")
	emit("sect_joined", {"actor": actor_id, "sect": sect_id})
	emit("sect_rank_changed", {"actor": actor_id, "rank": "service_disciple"})

func apply_rank(actor_id: String, rank: String) -> void:
	var c = game.character(actor_id)
	if c == null or c.training_sect.is_empty(): return
	var order: Array = ContentDB.config("sect_ranks").get("order", [])
	if order.find(rank) <= order.find(str(c.training_sect.get("rank", ""))): return
	c.training_sect.rank = rank
	emit("sect_rank_changed", {"actor": actor_id, "rank": rank})

func apply_contribution(actor_id: String, amount: int, source: String) -> void:
	var c = game.character(actor_id)
	if c == null or c.training_sect.is_empty(): return
	c.training_sect.contribution = maxi(0, int(c.training_sect.get("contribution", 0)) + amount)
	emit("contribution_changed", {"actor": actor_id, "value": c.training_sect.contribution, "delta": amount, "source": source})

func apply_reputation(actor_id: String, faction: String, amount: int) -> void:
	var c = game.character(actor_id)
	if c == null: return
	if not c.training_sect.has("reputation"): c.training_sect.reputation = {}
	var f := faction if faction != "" else str(c.training_sect.get("id", ""))
	c.training_sect.reputation[f] = int(c.training_sect.reputation.get(f, 0)) + amount
	emit("reputation_changed", {"actor": actor_id, "faction": f, "value": c.training_sect.reputation[f]})

func promote(c) -> Dictionary:
	var ranks: Array = ContentDB.config("sect_ranks").get("ranks", [])
	var order: Array = ContentDB.config("sect_ranks").get("order", [])
	var i := order.find(str(c.training_sect.get("rank", "")))
	if i < 0 or i + 1 >= order.size(): return fail("max_rank")
	var next: Dictionary = ranks[i + 1]
	if not RequirementRules.passes(next.get("requires", {}), game.ctx(c)):
		return fail("not_ready", {"text": RequirementRules.first_failure_text(next.requires, game.ctx(c))})
	apply_rank(c.id, str(next.id))
	return ok({"rank": next.id})
