class_name TrainingSectAuthority
extends Authority
## S20 · Training sect membership, rank, contribution and reputation per
## character. Daily missions are generated by the Quest authority on daily_reset.

func intents() -> Array:
	return ["take_promotion_trial", "leave_sect"]

func handle(intent: Dictionary) -> Dictionary:
	var c = char_of(intent)
	if c == null: return fail("no_character")
	match str(intent.type):
		"take_promotion_trial": return promote(c)
		"leave_sect": return fail("not_in_valley", {"text": "Leaving your sect is not possible in Act I."})
	return fail("unknown_intent")

func apply_join(actor_id: String, sect_id: String) -> void:
	var c = game.character(actor_id)
	var sect := ContentDB.entry("sects", sect_id)
	if c == null or sect.is_empty() or str(c.training_sect.get("id", "")) != "": return
	c.training_sect = {"id": sect_id, "rank": "service_disciple", "contribution": 0, "reputation": {sect_id: 10}}
	for m in sect.get("methods", []): game.progression.apply_learn_method(actor_id, str(m))
	if sect.has("token"): game.inventory.apply_add(actor_id, str(sect.token), 1, "sect")
	emit("sect_joined", {"actor": actor_id, "sect": sect_id})
	emit("sect_rank_changed", {"actor": actor_id, "rank": "service_disciple"})

func apply_rank(actor_id: String, rank: String) -> void:
	var c = game.character(actor_id)
	if c == null or c.training_sect.is_empty(): return
	var order: Array = ContentDB.config("sect_ranks").get("order", [])
	if order.find(rank) <= order.find(str(c.training_sect.get("rank", ""))): return
	c.training_sect.rank = rank
	emit("sect_rank_changed", {"actor": actor_id, "rank": rank})

func apply_contribution(actor_id: String, amount: int, source: String) -> void:
	var c = game.character(actor_id)
	if c == null or c.training_sect.is_empty(): return
	c.training_sect.contribution = maxi(0, int(c.training_sect.get("contribution", 0)) + amount)
	emit("contribution_changed", {"actor": actor_id, "value": c.training_sect.contribution, "delta": amount, "source": source})
	emit("currency_changed", {"currency": "contribution", "value": c.training_sect.contribution, "delta": amount, "source": source})

func apply_reputation(actor_id: String, faction: String, amount: int) -> void:
	var c = game.character(actor_id)
	if c == null: return
	if not c.training_sect.has("reputation"): c.training_sect.reputation = {}
	var f := faction if faction != "" else str(c.training_sect.get("id", ""))
	c.training_sect.reputation[f] = int(c.training_sect.reputation.get(f, 0)) + amount
	emit("reputation_changed", {"actor": actor_id, "faction": f, "value": c.training_sect.reputation[f]})

func promote(c) -> Dictionary:
	var ranks: Array = ContentDB.config("sect_ranks").get("ranks", [])
	var order: Array = ContentDB.config("sect_ranks").get("order", [])
	var i := order.find(str(c.training_sect.get("rank", "")))
	if i < 0 or i + 1 >= order.size(): return fail("max_rank")
	var next: Dictionary = ranks[i + 1]
	if not RequirementRules.passes(next.get("requires", {}), game.ctx(c)):
		return fail("not_ready", {"text": RequirementRules.first_failure_text(next.requires, game.ctx(c))})
	apply_rank(c.id, str(next.id))
	return ok({"rank": next.id})
